INSERT INTO TRAINEE (ID, FIRSTNAME, SURNAME) VALUES(1, 'Nawid', 'Mujadidi'); 

INSERT INTO TRAINEE (ID, FIRSTNAME, SURNAME) VALUES(2, 'Hussein', 'Tejan'); 

INSERT INTO TRAINEE (ID, FIRSTNAME, SURNAME) VALUES(3, 'Chris', 'Darrall'); 

INSERT INTO SUBJECT (ID, SUBJECTNAME, SCORE, TRAINEE_ID) VALUES(1, 'Linux', '3', 1);
INSERT INTO SUBJECT (ID, SUBJECTNAME, SCORE, TRAINEE_ID) VALUES(2, 'Java', '5', 1);
INSERT INTO SUBJECT (ID, SUBJECTNAME, SCORE, TRAINEE_ID) VALUES(3, 'JavaScript', '4', 1);

INSERT INTO SUBJECT (ID, SUBJECTNAME, SCORE, TRAINEE_ID) VALUES(4, 'JavaScript', '5', 2);
INSERT INTO SUBJECT (ID, SUBJECTNAME, SCORE, TRAINEE_ID) VALUES(5, 'Java', '4', 2);
INSERT INTO SUBJECT (ID, SUBJECTNAME, SCORE, TRAINEE_ID) VALUES(6, 'Ruby', '3', 2);

INSERT INTO SUBJECT (ID, SUBJECTNAME, SCORE, TRAINEE_ID) VALUES(7, 'Java', '5', 3);
INSERT INTO SUBJECT (ID, SUBJECTNAME, SCORE, TRAINEE_ID) VALUES(8, 'JavaScript', '5', 3);
INSERT INTO SUBJECT (ID, SUBJECTNAME, SCORE, TRAINEE_ID) VALUES(9, 'Linux', '5', 3);

