INSERT INTO TRAINEE (ID, FIRSTNAME, SURNAME) VALUES(1, 'John', 'Doe'); 

INSERT INTO TRAINEE (ID, FIRSTNAME, SURNAME) VALUES(2, 'Jane', 'Doe'); 

INSERT INTO TRAINEE (ID, FIRSTNAME, SURNAME) VALUES(3, 'Jim', 'Taylor'); 

INSERT INTO SUBJECT (ID, SUBJECTNAME, SCORE, TRAINEE_ID) VALUES(1, 'Java', '5', 3);